config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resource :address, only: [:show, :update, :create, :destroy]
    resource :reservations, only: [:show]
  end

  resources :books do
    resource :reservations, only: [:show]
  end

  resources :reservations

  root 'welcome#index'
end

app/models/adress.rb
class Adress < ApplicationRecord
    belongs_to :user, optional: true 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reservations
    has_many :users, through: :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservations
    has_many :books, through: :reservations

    has_one :address

end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    
    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
 
        if @book.save
            redirect_to @book
        else
            render 'new'
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        
        if @book.update(book_params)
            redirect_to @book
        else
            render 'edit'
        end
    end     
    
    def destroy
        @book = Book.find(params[:id])
        @book.destroy
       
        redirect_to books_path
    end

    private
    def book_params
        params.require(:book).permit(:title, :author, :cod)
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    def index
        @reservations = Reservation.all
    end
    
    def show
        @reservation = Reservation.find(params[:id])
    end

    def new
        @reservation = Reservation.new
    end

    def create
        @reservation = Reservation.new(reservation_params)
 
        if @reservation.save
            redirect_to @reservation
        else
            render 'new'
        end
    end

    def edit
        @reservation = Reservation.find(params[:id])
    end

    def update
        @reservation = Reservation.find(params[:id])
        
        if @reservation.update(reservation_params)
            redirect_to @reservation
        else
            render 'edit'
        end
    end     
    
    def destroy
        @reservation = Reservation.find(params[:id])
        @reservation.destroy
       
        redirect_to reservations_path
    end

    private
    def reservation_params
        params.require(:reservation).permit(:data_entrega, :user_id, :book_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
 
        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        
        if @user.update(user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end     
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
       
        redirect_to users_path
    end

    private
    def user_params
        params.require(:user).permit(:name, :matricula, :cpf)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>
 
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@book.errors.count, "error") %> prohibited
          this book from being saved:
        </h2>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>
   
    <p>
      <%= form.label :cod %><br>
      <%= form.text_area :cod %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing Books</h1>
<%= link_to 'New Book', new_book_path %>
<hr>
<table>
  <tr>
    <th>Título</th>
    <th>Author</th>
    <th>Cód.</th>
    <th colspan="3"></th>
  </tr>
 
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.cod %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book_path(book),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', welcome_index_path %>

app/views/books/new.html.erb
<h1>New Book</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h2>Book</h2>

<p>
  <strong>Título:</strong>
  <%= @book.title %>
</p>
 
<p>
  <strong>Autor:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Código:</strong>
  <%= @book.cod %>
</p>
<hr>

<%= link_to 'Edit', edit_book_path(@book) %> 
 
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with model: @reservation, local: true do |form| %>
 
    <% if @reservation.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@reservation.errors.count, "error") %> prohibited
          this reservation from being saved:
        </h2>
        <ul>
          <% @reservation.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   

    <table>
    <tr>
      <th>Data Entrega</th>    
      <th>Usuário</th>    
      <th>Livro</th>   
    </tr>   
   
      <tr>
        <td> <%= form.text_field :data_entrega %></td>    
        <td> <%= form.collection_select(:user_id, User.all, :id, :name, :include_blank => true) %></td>    
        <td> <%= form.collection_select(:book_id, Book.all, :id, :title, :include_blank => true) %></td>        
      </tr>
  </table>   

  <p>
  <%= form.submit %>
</p>
  <% end %>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing Reservations</h1>
<%= link_to 'New Reservation', new_reservation_path %>
<hr>
<table>
  <tr>
    <th>Data Entrega</th>    
    <th colspan="3"></th>
  </tr>
 
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.data_entrega %></td>
   
      <td><%= link_to 'Show', reservation_path(reservation) %></td>
      <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
      <td><%= link_to 'Destroy', reservation_path(reservation),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', welcome_index_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<h2>Reservation</h2>

<p>
  <strong>Data da Entrega:</strong>
  
  <%= @reservation.data_entrega %>
</p>
 

<%= link_to 'Edit', edit_reservation_path(@reservation) %> 
 
<%= link_to 'Back', reservations_path %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
 
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited
          this user from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
    <%= form.label :matricula %><br>
    <%= form.text_field :matricula %>
  </p>
   
    <p>
      <%= form.label :cpf %><br>
      <%= form.text_area :cpf %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<%= link_to 'New User', new_user_path %>
<hr>
<table>
  <tr>
    <th>Nome</th>
    <th>Matricula</th>
    <th>CPF</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.matricula %></td>
      <td><%= user.cpf %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Back', welcome_index_path %>

app/views/users/new.html.erb
<h1>New User</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>User</h2>

<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>Matrícula:</strong>
  <%= @user.matricula %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @user.cpf %>
</p>
<hr>

<h2>Adress</h2>


<%= link_to 'Edit', edit_user_path(@user) %> 
 
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to library</h1>

<p><%= link_to 'Users', controller: 'users' %></p>
<p><%= link_to 'Books', controller: 'books' %></p>
<p><%= link_to 'Reservations', controller: 'reservations' %></p>